repos:
  - repo: local
    hooks:
      - id: format-check
        name: Run make format
        entry: make format
        language: system
        pass_filenames: false
      - id: lint-check
        name: Run make lint
        entry: make lint
        language: system
        pass_filenames: false