version: '3.8'
services:
  streamlit-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501: 8501"
    depends_on:
      - chunkingService
      - embeddingService
      - loadersService
      - retrieversService
      - vectorStoreService
  chunkingService:
    build:
      context: ./src/chunking
      dockerfile: Dockerfile.chunking
    ports:
      - "5000:5000"
  embeddingService:
    build:
      context: ./src/embedding
      dockerfile: Dockerfile.embedding
    ports:
      - "5001:5001"
  loadersService:
    build:
      context: ./src/loaders
      dockerfile: Dockerfile.loaders
    ports:
      - "5002:5002"
  retrieversService:
    build:
      context: ./src/retrievers
      dockerfile: Dockerfile.retrievers
    ports:
      - "5003:5003"
  vectorStoreService:
    build:
      context: ./src/vectorStoreService
      dockerfile: Dockerfile.vectorStore
    ports:
      - "5004:5004"
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
volumes:
  qdrant_storage

