version: '3.11.5'

services:
  streamlit-app:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount a volume for saved files
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - VECTOR_STORE_NAME=regulaciones_mx
      - MODEL_EMBEDDING=sentence-transformers/all-MiniLM-L6-v2
      - VECTOR_SIZE=384
        


  qdrant:
    image: qdrant/qdrant:v1.3.2
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:

