version: '3.11'

services:
  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount a volume for saved files
    depends_on:
      - rag-qdrant
    environment:
      - QDRANT_HOST=rag-qdrant
      - QDRANT_PORT=6333
      - VECTOR_STORE_NAME=regulaciones_mx
      - MODEL_EMBEDDING=distiluse-base-multilingual-cased-v2
      - VECTOR_SIZE=512
      - REGULATIONS_FOLDER=data/regutations
      - EMBEDDINGS_FOLDER=data/embeddings
      - CHUNKING_FOLDER=data/chunckings


  rag-qdrant:
    image: qdrant/qdrant:v1.3.2
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:

