version: '3.11.5'

services:
  streamlit-app:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount a volume for saved files
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  qdrant:
    image: qdrant/qdrant:v1.3.2
    container_name: qdrant
    ports:
      - "6333:6333"
    volumens:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:

