version: '3.11'

services:
  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount a volume for saved files
    depends_on:
      - rag-qdrant
    environment:
      - QDRANT_HOST=rag-qdrant
      - QDRANT_PORT=6333
      - VECTOR_STORE_NAME=regulaciones_mx
      - MODEL_EMBEDDING=distiluse-base-multilingual-cased-v2
      - VECTOR_SIZE=512
      - REGULATIONS_FOLDER=data/regulations
      - EMBEDDINGS_FOLDER=data/embeddings
      - CHUNKING_FOLDER=data/chunks
      - OLLAMA_HOST=ollama-llm
      - OLLAMA_PORT=11434
    networks:
      - default
  
  rag-qdrant:
    image: qdrant/qdrant:v1.3.2
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - default

  ollama-llm:
    image: ollama/ollama:latest
    deploy:
      resources:
        limits:
          memory: 8GiB
    container_name: ollama-llm
    ports:
      - "11434:11434"  # Ollama's default API port
    volumes:
      - ./ollama_models:/root/.ollama  # Add this for persistent model storage
    networks:
      - default
    

volumes:
  qdrant_data:
  ollama_models:

