# Usa una imagen base de Python
FROM python:3.9.10

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY src/app.py requirements.txt ./

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto de la app de Streamlit
EXPOSE 8501

# Comando para ejecutar la app de Streamlit
CMD ["streamlit", "run", "main_app.py", "--server.enableCORS=false"]